django/project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.views.generic import RedirectView

from admin_rest.models import site
from project import settings
from django.conf.urls import url

urlpatterns = [
    path("", RedirectView.as_view(url="admin/", permanent=True)),
    path("admin/api/", site.urls),
    path("admin/", admin.site.urls),
    path("searchapp/", include(("searchapp.urls", "searchapp"), namespace="searchapp")),
    path("social-auth/", include("social_django.urls", namespace="social-view")),
    path("auth/", include("rest_framework_social_oauth2.urls")),
    path("glossary/", include(("glossary.urls", "glossary"), namespace="glossary")),
    path("obligations/", include(("obligations.urls", "obligations"), namespace="obligations")),
    path("dblogging/", include(("dblogging.urls", "dblogging"), namespace="dblogging")),
    path("ht/", include("health_check.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django/searchapp/urls.py
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.urls import path, re_path, include
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

import os

from searchapp import views

schema_view = get_schema_view(
    openapi.Info(
        title="Catalogue Manager API",
        default_version="v1",
        description="Documentation for REST API",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="nobody@crosslang.com"),
        license=openapi.License(name="BSD License"),
    ),
    url=os.environ["DJANGO_BASE_URL"],
    patterns=[path("searchapp/", include(("searchapp.urls", "searchapp"), namespace="searchapp"))],
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path("login/", auth_views.LoginView.as_view(template_name="searchapp/login.html"), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    # API
    # Swagger drf-yasg
    re_path(r"^swagger(?P<format>\.json|\.yaml)$", schema_view.without_ui(cache_timeout=0), name="schema-json"),
    path("swagger", schema_view.with_ui("swagger", cache_timeout=0), name="schema-swagger-ui"),
    path("redoc", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
    # Website
    path("api/websites", views.WebsiteListAPIView.as_view(), name="website_list_api"),
    path("api/website/<int:pk>", views.WebsiteDetailAPIView.as_view(), name="website_detail_api"),
    # Document
    path("api/documents", views.DocumentListAPIView.as_view(), name="document_list_api"),
    path("api/document/<uuid:pk>", views.DocumentDetailAPIView.as_view(), name="document_detail_api"),
    # EurLex Formex
    path("api/formex/urls/<str:celex>", views.FormexUrlsAPIView.as_view(), name="formex_urls_api"),
    path("api/formex/act/<str:celex>", views.FormexActAPIView.as_view(), name="formex_act_api"),
    # Attachment
    path("api/attachments", views.AttachmentListAPIView.as_view(), name="attachment_list_api"),
    path("api/attachment/<uuid:pk>", views.AttachmentDetailAPIView.as_view(), name="attachment_detail_api"),
    # State
    path("api/states", views.AcceptanceStateListAPIView.as_view(), name="state_list_api"),
    path("api/state/<int:pk>", views.AcceptanceStateDetailAPIView.as_view(), name="state_detail_api"),
    path("api/state/value", views.AcceptanceStateValueAPIView.as_view(), name="state_value_api"),
    # Comment
    path("api/comments", views.CommentListAPIView.as_view(), name="comment_list_api"),
    path("api/comment/<int:pk>", views.CommentDetailAPIView.as_view(), name="comment_detail_api"),
    # Tag
    path("api/tags", views.TagListAPIView.as_view(), name="tag_list_api"),
    path("api/tag/<int:pk>", views.TagDetailAPIView.as_view(), name="tag_detail_api"),
    # Document stats
    path("api/stats", views.DocumentStats.as_view(), name="document_stats"),
    # Super
    path("api/super", views.IsSuperUserAPIView.as_view(), name="super_api"),
    # Solr
    path("api/solrdocument/search/", views.SolrDocumentSearchPost.as_view(), name="solr_document_search_post_api"),
    # Django + SOLR
    path(
        "api/solrdocument/search/query/django/",
        views.SolrDocumentsSearchQueryDjango.as_view(),
        name="solr_document_search_query_django_api",
    ),
    path(
        "api/solrdocument/search/ro_query/django/",
        views.SolrDocumentsSearchQueryDjangoReportingObligation.as_view(),
        name="solr_document_search_query_django_by_ro_api",
    ),
    # SOLR ONLY
    path(
        "api/solrdocument/search/query/preanalyzed/",
        views.SolrDocumentsSearchQueryPreAnalyzed.as_view(),
        name="solr_document_search_query_preanalyzed_api",
    ),
    path(
        "api/solrdocument/search/query/preanalyzed/<doc_id>",
        views.SolrDocumentSearchQueryPreAnalyzed.as_view(),
        name="solr_search_query_with_doc_id_preanalyzed_api",
    ),
    # solr_get_preanalyzed_for_doc
    path("api/solrdocuments/like/<id>", views.SimilarDocumentsAPIView.as_view(), name="similar_documents_api"),
    # Export
    path("api/export/launch", views.ExportDocumentsLaunch.as_view(), name="export_launch_api"),
    path("api/export/status/<task_id>", views.ExportDocumentsStatus.as_view(), name="export_status_api"),
    path("api/export/download/<task_id>", views.ExportDocumentsDownload.as_view(), name="export_download_api"),
    # Bookmarks
    path("api/bookmarks", views.BookmarkListAPIView.as_view(), name="bookmark_list_api"),
    path("api/bookmarks/<document_id>", views.BookmarkDetailAPIView.as_view(), name="bookmark_detail_api"),
    # Dropdown: celex
    path("api/filters/celex", views.CelexListAPIView.as_view(), name="celex_list_api"),
    # Dropdown: type
    path("api/filters/type", views.TypeListAPIView.as_view(), name="type_list_api"),
    # Dropdown: status
    path("api/filters/status", views.StatusListAPIView.as_view(), name="status_list_api"),
    # Dropdown: eli
    path("api/filters/eli", views.EliListAPIView.as_view(), name="eli_list_api"),
    # Dropdown: eli
    path("api/filters/author", views.AuthorListAPIView.as_view(), name="eli_list_api"),
    # Dropdown: eli
    path("api/filters/effectdate", views.DateOfEffectListAPIView.as_view(), name="eli_list_api"),
    path("api/version", views.AppVersion.as_view(), name="app_version_api"),
    # Usernames
    path("api/userlist", views.UserListAPIView.as_view(), name="user_list_api"),
    # Public API for Solr
    path("api/solr/query", views.SolrPublicDocumentSearch.as_view(), name="solr_public_query_api"),
]

django/project/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Search app</title>
    {% load static %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
            integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
            integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>
<body>
<div class="container">
    <nav class="nav navbar-expand-lg navbar-light bg-light mb-4 p-4">
        <a class="navbar-brand" href="{% url 'searchapp:websites' %}">Catalogue Manager <span class="text-danger">(concept)</span></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-item nav-link {% if nav == 'scraping' %}active{% endif %}"
                   href="{% url 'scraping:scraping' %}">Scraping</a>
                <a class="nav-item nav-link {% if nav == 'websites' %}active{% endif %}"
                   href="{% url 'searchapp:websites' %}">Browse data</a>
                <a class="nav-item nav-link {% if nav == 'documents' %}active{% endif %}"
                   href="{% url 'searchapp:document_search' %}">Document search</a>
            </div>
        </div>
        <form class="logout-link" action="{% url 'searchapp:logout' %}" method="post">
            {% csrf_token %}
            <button class="btn btn-link" type="submit">Logout</button>
        </form>
    </nav>
    {% block content %}{% endblock %}
</div>
</body>
</html>

django/project/templates/base_login.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Search app</title>
    {% load static %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
            integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>
<body>
<div class="container min-vh-100">
    {% block content %}{% endblock %}
</div>
</body>
</html>